close all;
clear;
clc;

function aperta(ObjH, eventdata, tecla)

  #disp(tecla)

  % Call DTMF
  fs = 8000; # Frequencia de amostragem [Hz]
  sinal = dtmf_gen(tecla, fs);

  % Grava audio
  #audiowrite('sinal.wav', sinal, fs);

  % Toca audio
  playblocking(audioplayer(sinal, fs, 24));

  % Transformada de Fourrier para o sinal (Verificação)
  #figure(1, 'name', 'FFT', 'numbertitle', 'off');
  #stem(1:(8000/length(sinal)):8000, abs(fft(sinal)), '.');

  % Call servico
  servico(sinal, fs);
endfunction

% GUI
MainFrm = figure(2, 'name', 'DTMF', 'numbertitle', 'off');

% Container de texto
texto = uipanel(MainFrm, ...
  'units', 'normalized', ...
  'position', [0, 0.5, 1, 0.5]);

txt_frm = uicontrol(texto, ...
  'style', 'text', ...
  'string', '', ...
  'verticalalignment', 'top');

% Conteiner plot
grafico = uipanel(MainFrm, ...
  'units', 'normalized', ...
  'position', [0.5, 0, 0.6, 0.5]);

subplot(2, 1, 1);
plot([1, 2, 3]);

subplot(2, 1, 2);
plot([3, 2, 1]);

% Conteiner teclado
teclado = uipanel(MainFrm, ...
  'units', 'normalized', ...
  'position', [0, 0, 0.4, 0.5]);

uicontrol(teclado, ...
  'style', 'pushbutton', ...
  'string', '1', ...
  'units', 'normalized', ...
  'position', [0, 0.75, 0.25, 0.25], ...
  'callback', {@aperta, 1});

uicontrol(teclado, ...
  'style', 'pushbutton', ...
  'string', '2', ...
  'units', 'normalized', ...
  'position', [0.25, 0.75, 0.25, 0.25], ...
  'callback', {@aperta, 2});

uicontrol(teclado, ...
  'style', 'pushbutton', ...
  'string', '3', ...
  'units', 'normalized', ...
  'position', [0.50, 0.75, 0.25, 0.25], ...
  'callback', {@aperta, 3});

uicontrol(teclado, ...
  'style', 'pushbutton', ...
  'string', '4', ...
  'units', 'normalized', ...
  'position', [0, 0.5, 0.25, 0.25], ...
  'callback', {@aperta, 4});

uicontrol(teclado, ...
  'style', 'pushbutton', ...
  'string', '5', ...
  'units', 'normalized', ...
  'position', [0.25, 0.5, 0.25, 0.25], ...
  'callback', {@aperta, 5});

uicontrol(teclado, ...
  'style', 'pushbutton', ...
  'string', '6', ...
  'units', 'normalized', ...
  'position', [0.5, 0.5, 0.25, 0.25], ...
  'callback', {@aperta, 6});

uicontrol(teclado, ...
  'style', 'pushbutton', ...
  'string', '7', ...
  'units', 'normalized', ...
  'position', [0, 0.25, 0.25, 0.25], ...
  'callback', {@aperta, 7});

uicontrol(teclado, ...
  'style', 'pushbutton', ...
  'string', '8', ...
  'units', 'normalized', ...
  'position', [0.25, 0.25, 0.25, 0.25], ...
  'callback', {@aperta, 8});

uicontrol(teclado, ...
  'style', 'pushbutton', ...
  'string', '9', ...
  'units', 'normalized', ...
  'position', [0.5, 0.25, 0.25, 0.25], ...
  'callback', {@aperta, 9});

uicontrol(teclado, ...
  'style', 'pushbutton', ...
  'string', '0', ...
  'units', 'normalized', ...
  'position', [0.25, 0, 0.25, 0.25], ...
  'callback', {@aperta, 0});

uicontrol(teclado, ...
  'style', 'pushbutton', ...
  'string', '*', ...
  'units', 'normalized', ...
  'position', [0, 0, 0.25, 0.25], ...
  'callback', {@aperta, 10});

uicontrol(teclado, ...
  'style', 'pushbutton', ...
  'string', '#', ...
  'units', 'normalized', ...
  'position', [0.5, 0, 0.25, 0.25], ...
  'callback', {@aperta, 11});

uicontrol(teclado, ...
  'style', 'pushbutton', ...
  'string', 'A', ...
  'units', 'normalized', ...
  'position', [0.75, 0.75, 0.25, 0.25], ...
  'callback', {@aperta, 12});

uicontrol(teclado, ...
  'style', 'pushbutton', ...
  'string', 'B', ...
  'units', 'normalized', ...
  'position', [0.75, 0.5, 0.25, 0.25], ...
  'callback', {@aperta, 13});

uicontrol(teclado, ...
  'style', 'pushbutton', ...
  'string', 'C', ...
  'units', 'normalized', ...
  'position', [0.75, 0.25, 0.25, 0.25], ...
  'callback', {@aperta, 14});

uicontrol(teclado, ...
  'style', 'pushbutton', ...
  'string', 'D', ...
  'units', 'normalized', ...
  'position', [0.75, 0, 0.25, 0.25], ...
  'callback', {@aperta, 15});