close all;
clear;
clc;

function aperta(ObjH, eventdata, tecla, txt_frm, g1, g2)

  #disp(tecla)

  % Call DTMF
  fs = 8000; # Frequencia de amostragem [Hz]
  sinal = dtmf_gen(tecla, fs);

  % Grava audio
  #audiowrite('sinal.wav', sinal, fs);

  % Toca audio
  playblocking(audioplayer(sinal, fs, 24));

  % Transformada de Fourrier para o sinal (Verificação)
  #figure(1, 'name', 'FFT', 'numbertitle', 'off');
  #stem(1:(8000/length(sinal)):8000, abs(fft(sinal)), '.');

  % Inserindo dados nos gráficos
  l = length(sinal);
  x = 0:1/8000:l/fs;
  x(end) = [];
  set(g1, 'xdata', x);
  set(g1, 'ydata', sinal);
  set(g2, 'xdata', 1:(fs/length(sinal)):fs);
  set(g2, 'ydata', abs(fft(sinal)));

  % Call servico
  #texto = char([get(txt_frm, 'string'), 10, servico(sinal, fs)]);
  set(txt_frm, 'string', servico(sinal, fs));
endfunction

% GUI
MainFrm = figure(2, 'name', 'DTMF', 'numbertitle', 'off');

% Container de texto
texto = uipanel(MainFrm, ...
  'units', 'normalized', ...
  'position', [0, 0.5, 1, 0.5]);

txt_frm = uicontrol(texto, ...
  'style', 'text', ...
  'string', '', ...
  'verticalalignment', 'top', ...
  'horizontalalignment', 'left', ...
  'units', 'normalized', ...
  'position', [0, 0, 1, 1], ...
  'backgroundcolor', [1 1 1], ...
  'userdata', 1);

set(txt_frm, 'string', 'DTFM Sim');

% Conteiner plot
grafico = uipanel(MainFrm, ...
  'units', 'normalized', ...
  'position', [0.3, 0, 0.7, 0.5]);

#Setando Grafico 1
subplot(2, 1, 1, 'parent', grafico);
g1 = plot([1], 'marker', 'none');
title('Sinal');
xlabel('Tempo [s]');
grid on;
grid minor on;

#Setando Grafico 2
subplot(2, 1, 2, 'parent', grafico);
g2 = plot([1], 'marker', 'none');
title('Sinal (FFT)');
xlabel('Frequencia [Hz]');
grid on;
grid minor on;

% Conteiner teclado
teclado = uipanel(MainFrm, ...
  'units', 'normalized', ...
  'position', [0, 0, 0.3, 0.5]);

uicontrol(teclado, ...
  'style', 'pushbutton', ...
  'string', '1', ...
  'units', 'normalized', ...
  'position', [0, 0.75, 0.25, 0.25], ...
  'callback', {@aperta, 1, txt_frm, g1, g2});

uicontrol(teclado, ...
  'style', 'pushbutton', ...
  'string', '2', ...
  'units', 'normalized', ...
  'position', [0.25, 0.75, 0.25, 0.25], ...
  'callback', {@aperta, 2, txt_frm, g1, g2});

uicontrol(teclado, ...
  'style', 'pushbutton', ...
  'string', '3', ...
  'units', 'normalized', ...
  'position', [0.50, 0.75, 0.25, 0.25], ...
  'callback', {@aperta, 3, txt_frm, g1, g2});

uicontrol(teclado, ...
  'style', 'pushbutton', ...
  'string', '4', ...
  'units', 'normalized', ...
  'position', [0, 0.5, 0.25, 0.25], ...
  'callback', {@aperta, 4, txt_frm, g1, g2});

uicontrol(teclado, ...
  'style', 'pushbutton', ...
  'string', '5', ...
  'units', 'normalized', ...
  'position', [0.25, 0.5, 0.25, 0.25], ...
  'callback', {@aperta, 5, txt_frm, g1, g2});

uicontrol(teclado, ...
  'style', 'pushbutton', ...
  'string', '6', ...
  'units', 'normalized', ...
  'position', [0.5, 0.5, 0.25, 0.25], ...
  'callback', {@aperta, 6, txt_frm, g1, g2});

uicontrol(teclado, ...
  'style', 'pushbutton', ...
  'string', '7', ...
  'units', 'normalized', ...
  'position', [0, 0.25, 0.25, 0.25], ...
  'callback', {@aperta, 7, txt_frm, g1, g2});

uicontrol(teclado, ...
  'style', 'pushbutton', ...
  'string', '8', ...
  'units', 'normalized', ...
  'position', [0.25, 0.25, 0.25, 0.25], ...
  'callback', {@aperta, 8, txt_frm, g1, g2});

uicontrol(teclado, ...
  'style', 'pushbutton', ...
  'string', '9', ...
  'units', 'normalized', ...
  'position', [0.5, 0.25, 0.25, 0.25], ...
  'callback', {@aperta, 9, txt_frm, g1, g2});

uicontrol(teclado, ...
  'style', 'pushbutton', ...
  'string', '0', ...
  'units', 'normalized', ...
  'position', [0.25, 0, 0.25, 0.25], ...
  'backgroundcolor', [1 1 1], ...
  'callback', {@aperta, 0, txt_frm, g1, g2});

uicontrol(teclado, ...
  'style', 'pushbutton', ...
  'string', '*', ...
  'units', 'normalized', ...
  'position', [0, 0, 0.25, 0.25], ...
  'backgroundcolor', [153/255 190/255 255/255], ...
  'callback', {@aperta, 10, txt_frm, g1, g2});

uicontrol(teclado, ...
  'style', 'pushbutton', ...
  'string', '#', ...
  'units', 'normalized', ...
  'position', [0.5, 0, 0.25, 0.25], ...
  'backgroundcolor', [153/255 190/255 255/255], ...
  'callback', {@aperta, 11, txt_frm, g1, g2});

uicontrol(teclado, ...
  'style', 'pushbutton', ...
  'string', 'A', ...
  'units', 'normalized', ...
  'position', [0.75, 0.75, 0.25, 0.25], ...
  'backgroundcolor', [242/255 165/255 165/255], ...
  'callback', {@aperta, 12, txt_frm, g1, g2});

uicontrol(teclado, ...
  'style', 'pushbutton', ...
  'string', 'B', ...
  'units', 'normalized', ...
  'position', [0.75, 0.5, 0.25, 0.25], ...
  'backgroundcolor', [242/255 165/255 165/255], ...
  'callback', {@aperta, 13, txt_frm, g1, g2});

uicontrol(teclado, ...
  'style', 'pushbutton', ...
  'string', 'C', ...
  'units', 'normalized', ...
  'position', [0.75, 0.25, 0.25, 0.25], ...
  'backgroundcolor', [242/255 165/255 165/255], ...
  'callback', {@aperta, 14, txt_frm, g1, g2});

uicontrol(teclado, ...
  'style', 'pushbutton', ...
  'string', 'D', ...
  'units', 'normalized', ...
  'position', [0.75, 0, 0.25, 0.25], ...
  'backgroundcolor', [242/255 165/255 165/255], ...
  'callback', {@aperta, 15, txt_frm, g1, g2});